config/routes.rb
Rails.application.routes.draw do
  resources :student_guardians
  resources :guardians
  resources :staffs
  resources :classlists
  resources :sections
  resources :subjects
  resources :teachers
  resources :students
  resources :departments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/staff.rb
class Staff < ApplicationRecord
  belongs_to :department
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: %i[ show edit update destroy ]

  # GET /staffs or /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1 or /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs or /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save

        #Add employee_count to Department
        @staff.department.increment!(:employee_count)

        format.html { redirect_to @staff, notice: "Staff was successfully created." }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1 or /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: "Staff was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1 or /staffs/1.json
  def destroy
    @staff.destroy!

    #Subtract employee_count to Department
    @staff.department.decrement!(:employee_count)

    respond_to do |format|
      format.html { redirect_to staffs_path, notice: "Staff was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def staff_params
      params.expect(staff: [ :name, :email, :monthly_salary, :status, :department_id ])
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= form_with(model: staff) do |form| %>
  <% if staff.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
        <% staff.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :monthly_salary, style: "display: block" %>
    <%= form.text_field :monthly_salary %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :department_id, "Department", style: "display: block" %>
    <%= form.collection_select :department_id, Department.all, :id, :name, prompt: "Select a department" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/staffs/_staff.html.erb
<div id="<%= dom_id staff %>">
  <p>
    <strong>Name:</strong>
    <%= staff.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= staff.email %>
  </p>

  <p>
    <strong>Monthly salary:</strong>
    <%= staff.monthly_salary %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= staff.status %>
  </p>

  <p>
    <strong>Department:</strong>
    <%= staff.department_id %>
  </p>

</div>

app/views/staffs/edit.html.erb
<% content_for :title, "Editing staff" %>

<h1>Editing staff</h1>

<%= render "form", staff: @staff %>

<br>

<div>
  <%= link_to "Show this staff", @staff %> |
  <%= link_to "Back to staffs", staffs_path %>
</div>

app/views/staffs/index.html.erb
 

<% content_for :title, "Staffs" %>

<h1>Staffs</h1>

<div id="staffs">
  <% @staffs.each do |staff| %>
    <%= render staff %>
    <p>
      <%= link_to "Show this staff", staff %>
    </p>
  <% end %>
</div>

<%= link_to "New staff", new_staff_path %>

app/views/staffs/new.html.erb
<% content_for :title, "New staff" %>

<h1>New staff</h1>

<%= render "form", staff: @staff %>

<br>

<div>
  <%= link_to "Back to staffs", staffs_path %>
</div>

app/views/staffs/show.html.erb
 

<%= render @staff %>

<div>
  <%= link_to "Edit this staff", edit_staff_path(@staff) %> |
  <%= link_to "Back to staffs", staffs_path %>

  <%= button_to "Destroy this staff", @staff, method: :delete %>
</div>