config/routes.rb
Rails.application.routes.draw do
  resources :student_guardians
  resources :guardians
  resources :staffs
  resources :classlists
  resources :sections
  resources :subjects
  resources :teachers
  resources :students
  resources :departments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :department
  has_many :classlists, dependent: :destroy
  has_many :sections, through: :classlists, dependent: :destroy
  has_many :student_guardians, dependent: :destroy
  has_many :guardians, through: :student_guardians, dependent: :destroy
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save

        #Add student_count to Department
        @student.department.increment!(:student_count)

        format.html { redirect_to @student, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy!

    #Subtract employee_count to Department
    @student.department.decrement!(:student_count)

    respond_to do |format|
      format.html { redirect_to students_path, notice: "Student was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.expect(student: [ :name, :year_level, :program, :department_id ])
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <div class="card shadow mt-2 ms-1 me-1">
    <div class="card-header d-flex justify-content-between align-items-center" style="background-color: #cfe2ff;">
      <% if student.new_record? %>
        <h2 class="mb-0 fw-bold">New Student</h2>
        <div>
          <%= link_to "Back to Students", students_path, class: "btn btn-secondary me-2" %>
          <%= form.submit(class: "btn btn-success") %>
        </div>
        <% else %>
        <div class="d-flex align-items-center">
          <h2 class="mb-0 fw-bold">Edit Student</h2>
          <%= link_to "Show this Student", student, class: "btn btn-outline-primary ms-2" %>
        </div>
        <div>
          <%= link_to "Back to Students", students_path, class: "btn btn-secondary me-2" %>
          <%= form.submit(class: "btn btn-success") %>
        </div>
        <% end %>
    </div>
    <div class="card-body">
      <% if student.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

          <ul>
            <% student.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-3">
        <%= form.label :name, class: "form-label fw-bold"%>
        <%= form.text_field :name, class: "form-control", placeholder: "Enter Student Name" %>
      </div>

      <div class="mb-3">
        <%= form.label :year_level, class: "form-label fw-bold"%>
        <%= form.number_field :year_level, class: "form-control", placeholder: "Enter Year Level" %>
      </div>

      <div class="mb-3">
        <%= form.label :program, class: "form-label fw-bold"%>
        <%= form.text_field :program, class: "form-control", placeholder: "Enter Program" %>
      </div>

      <div class="mb-3">
        <%= form.label :department_id, "Department", class: "form-label fw-bold" %>
        <%= form.collection_select :department_id, Department.all, :id, :name, {prompt: "Select a Department"}, {class: "form-select"}%>
      </div>
    </div>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Name:</strong>
    <%= student.name %>
  </p>

  <p>
    <strong>Year level:</strong>
    <%= student.year_level %>
  </p>

  <p>
    <strong>Program:</strong>
    <%= student.program %>
  </p>

  <p>
    <strong>Department:</strong>
    <%= student.department_id %>
  </p>
  
  <p>
    <strong>Number of Units:</strong>
    <%= student.number_of_units %>
  </p>

  <p>
    <strong>Total Assessment:</strong>
    <%= student.total_assessment %>
  </p>

  <p>
    <strong>Number of Guardian:</strong>
    <%= student.number_of_guardians %>
  </p>

</div>

app/views/students/edit.html.erb
<% content_for :title, "Editing student" %>

<%= render "form", student: @student %>

<br>

app/views/students/index.html.erb
<div class="d-flex justify-content-between align-items-center mb-2">
  <p class="fs-2 fw-bold mb-0">List of Students</p>
  <%= link_to new_student_path, class: "btn btn-success fs-5" do%>
    <i class="bi bi-person-plus"></i>
    New Student
  <% end %>
</div>
<table class="table table-striped table-bordered table-hover">
    <thead>
      <tr class="table-primary">
        <th>Name</th>
        <th>Year</th>
        <th>Program</th>
        <th>Units</th>
        <th>Total Assessment</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student| %>
        <tr>
          <td style="width: 24%"><%= student.name%></td>
          <td style="width: 10%"><%= student.year_level%></td>
          <td style="width: 14%"><%= student.program%></td>
          <td style="width: 10%"><%= student.number_of_units%></td>
          <td style="width: 24%"><%= student.total_assessment%></td>
          <td style="width: 18%">
            <%= link_to student, class: "btn btn-sm btn-primary" do%>
              <i class="bi bi-eye"></i>
              Show
            <% end %>
            <%= link_to edit_student_path(student), class: "btn btn-sm btn-warning" do%>
              <i class="bi bi-pencil-square"></i>
              Edit
            <% end %>
            <%= button_to student, method: :delete, data: { turbo_confirm: false }, form: { data: { turbo: true }, class: "d-inline"}, class: "btn btn-sm btn-danger" do %>
              <i class="bi bi-trash"></i>
              Delete
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/students/new.html.erb
<% content_for :title, "New student" %>

<%= render "form", student: @student %>

<br>

app/views/students/show.html.erb
<div class="container-fluid m-1 bg-success-subtle text-center rounded-2 shadow">
  <span class="fs-1 fw-bold"> Student Info </span>
</div>
<div class="card shadow mt-2 ms-1 me-1 p-2">
  <div class="card-header pt-0 pb-2">
    <h1 class="mb-0 fw-bold"><%= @student.name %></h1>
    <p class="m-0"><%= @student.year_level %> | <%= @student.program %> | <%= @student.department.name %></p>
  </div>

  <div class="card-body p-2">
    <p><strong> No. of Units: </strong> <%= @student.number_of_units %></p>
    <p><strong> Total Assessment: </strong> <%= @student.total_assessment %></p>
    <p><strong> No. of Guardians: </strong> <%= @student.number_of_guardians %></p>
  </div>

  <h4 class="m-1 fw-bold">
    <i class="bi bi-book"></i>
    List of Subjects: 
  </h4>
  <table class="table table-bordered table-striped">
    <thead class="table table-primary">
      <tr>
        <th> Section </th>
        <th> Subject </th>
        <th> Units </th>
        <th> Teacher </th>
      </tr>
    </thead>
    <tbody>
      <% @student.classlists.each do |classlist| %>
        <tr>
          <td><%= classlist.section.name %></td>
          <td><%= classlist.section.subject.name %></td>
          <td><%= classlist.section.subject.number_of_units %></td>
          <td><%= classlist.section.subject.teacher.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="d-flex justify-content-between mt-2 mb-4 align-items-center">
    <div>
      <%= link_to "Back to students", students_path, class: "btn btn-secondary ms-2" %>
    </div>
    <div class="d-flex flex-row">
      <%= link_to edit_student_path(@student), class: "btn btn-warning me-2" do%>
        <i class="bi bi-pencil-square"></i>
        Edit
      <% end %>
      <%= button_to student_path(@student), method: :delete, data: { turbo_confirm: false }, form: { data: { turbo: true } }, class: "btn btn-danger" do %>
        <i class="bi bi-trash"></i>
        Delete
      <% end %>
    </div>  
  </div>
</div>