config/routes.rb
Rails.application.routes.draw do
  resources :student_guardians
  resources :guardians
  resources :staffs
  resources :classlists
  resources :sections
  resources :subjects
  resources :teachers
  resources :students
  resources :departments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/classlist.rb
class Classlist < ApplicationRecord
  belongs_to :student
  belongs_to :section
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :students, dependent: :destroy
    has_many :teachers, dependent: :destroy
    has_many :staffs, dependent: :destroy
end

app/models/guardian.rb
class Guardian < ApplicationRecord
    has_many :student_guardians, dependent: :destroy
    has_many :students, through: :student_guardians, dependent: :destroy
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :subject
  has_many :classlists, dependent: :destroy
  has_many :students, through: :classlists, dependent: :destroy
end

app/models/staff.rb
class Staff < ApplicationRecord
  belongs_to :department
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :department
  has_many :classlists, dependent: :destroy
  has_many :sections, through: :classlists, dependent: :destroy
  has_many :student_guardians, dependent: :destroy
  has_many :guardians, through: :student_guardians, dependent: :destroy
end

app/models/student_guardian.rb
class StudentGuardian < ApplicationRecord
  belongs_to :student
  belongs_to :guardian
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :teacher
  has_many :sections, dependent: :destroy
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :department
  has_many :subjects, dependent: :destroy
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: %i[ show edit update destroy ]

  # GET /staffs or /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1 or /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs or /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save

        #Add employee_count to Department
        @staff.department.increment!(:employee_count)

        format.html { redirect_to @staff, notice: "Staff was successfully created." }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1 or /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: "Staff was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1 or /staffs/1.json
  def destroy
    @staff.destroy!

    #Subtract employee_count to Department
    @staff.department.decrement!(:employee_count)

    respond_to do |format|
      format.html { redirect_to staffs_path, notice: "Staff was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def staff_params
      params.expect(staff: [ :name, :email, :monthly_salary, :status, :department_id ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classlists_helper.rb
module ClasslistsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/guardians_helper.rb
module GuardiansHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Helloworldapplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <!-- Bootstrap CSS CDN -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
    >
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">
  </head>

  <body class="bg-light">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand fs-2 fw-bold p-0" href="#">
        <span class="ms-2">School Manager</span>
      </a>
    </nav>

    <div class="d-flex flex-row">
      <ul class="nav nav-underline flex-column bg-dark p-2" style="height: 100vh; width: 200px">
        <li class="nav-item">
          <%= link_to students_path, class: "nav-link text-white d-flex align-items-center m-auto" do%>
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 256 256" fill="currentColor"><path d="m227.79 52.62l-96-32a11.85 11.85 0 0 0-7.58 0l-96 32A12 12 0 0 0 20 63.37a6.05 6.05 0 0 0 0 .63v80a12 12 0 0 0 24 0V80.65l23.71 7.9a67.92 67.92 0 0 0 18.42 85A100.36 100.36 0 0 0 46 209.44a12 12 0 1 0 20.1 13.11C80.37 200.59 103 188 128 188s47.63 12.59 61.95 34.55a12 12 0 1 0 20.1-13.11a100.36 100.36 0 0 0-40.18-35.92a67.92 67.92 0 0 0 18.42-85l39.5-13.17a12 12 0 0 0 0-22.76Zm-99.79-8L186.05 64L128 83.35L70 64ZM172 120a44 44 0 1 1-81.06-23.71l33.27 11.09a11.89 11.89 0 0 0 7.58 0l33.27-11.09A43.85 43.85 0 0 1 172 120Z"/></svg>
            Students
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to teachers_path, class: "nav-link text-white d-flex align-item-center m-auto" do%>
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 256 256" fill="currentColor"><path d="M56 84a12 12 0 0 1 12-12h120a12 12 0 0 1 12 12v88a12 12 0 0 1-24 0V96H68a12 12 0 0 1-12-12Zm180-28v144a20 20 0 0 1-20 20h-66.74a12 12 0 0 1-11.4-8.26a36 36 0 0 0-67.74 0A12 12 0 0 1 58.74 220H40a20 20 0 0 1-20-20V56a20 20 0 0 1 20-20h176a20 20 0 0 1 20 20ZM104 164a16 16 0 1 0-16-16a16 16 0 0 0 16 16ZM212 60H44v136h6.92a60.18 60.18 0 0 1 21.76-23.16a40 40 0 1 1 62.64 0A60.18 60.18 0 0 1 157.08 196H212Z"/></svg>
            Teachers
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to sections_path, class: "nav-link text-white" do%>
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 20h.01M4 20h.01M8 20h.01M12 20h.01M16 20h.01M20 4h.01M4 4h.01M8 4h.01M12 4h.01M16 4v.01M4 9a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v6a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1z"/></svg> 
            Sections
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to departments_path, class: "nav-link text-white" do%>
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24"><path fill="currentColor" d="M21 10h-2V4h1V2H4v2h1v6H3a1 1 0 0 0-1 1v9h20v-9a1 1 0 0 0-1-1zm-7 8v-4h-4v4H7V4h10v14h-3z"/><path fill="#000000" d="M9 6h2v2H9zm4 0h2v2h-2zm-4 4h2v2H9zm4 0h2v2h-2z"/></svg>
            Dept
          <% end %>
        </li>
      </ul>
      
      <main class="container-fluid m-2">
        <% flash.each do |key, message| %>
          <div class="alert alert-<%= key == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
            <%= message %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>
        <%= yield %>
      </main>
    </div>
    
    <!-- Bootstrap JS CDN (Optional for dropdowns, nav, etc.) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js">
    </script>
  </body>
</html>